### ISSUE TITLE
Bugs in Notification in v1.8

### ISSUE THREAD

**Issue by dev-tushar11** [SATYAJIT1910/MediClock#10]
Only one Notification for a single data comes up in case of more than one data having same Notification time

**Comment by SATYAJIT1910** [comment]
Alarms at the same time are coming but getting overwritten, so the user is only able to see one alarm. We can leave a notification for the missed alarms like Google Clock.

**Comment by SATYAJIT1910** [comment]
Now the user needs to manually dismiss all the activities for all the medicines, even though after first dismiss the alarm and vibration will be stopped.
